"use client";

import { useState, useTransition } from "react";
import { Activity, ArrowDownLeft, ArrowUpRight, Check, Clock3, Copy, ExternalLink, Filter, History, RefreshCw, ShieldAlert, WalletCards } from "lucide-react";
import { celo, celoSepolia } from "wagmi/chains";
import { useAccount, useChainId, useSwitchChain } from "wagmi";
import { useRouter } from "next/navigation";
import { ConnectWalletButton } from "@/ConnectWalletButton";
import { shortenAddress } from "@/lib/utils";

const filters = ["All", "Sent", "Received", "Donations", "Agent", "Reforestation", "Pending", "Failed"] as const;
type FilterName = (typeof filters)[number];

export default function ActivityPage() {
  const { address, chain, isConnected } = useAccount();
  const chainId = useChainId();
  const { switchChain, isPending: isSwitching } = useSwitchChain();
  const [filter, setFilter] = useState<FilterName>("All");
  const [query, setQuery] = useState("");
  const [refreshing, startRefresh] = useTransition();
  const router = useRouter();
  const [selected, setSelected] = useState<ActivityItem | null>(null);
  const wrongNetwork = isConnected && chainId !== celo.id && chainId !== celoSepolia.id;
  const activity: ActivityItem[] = [];
  const visibleActivity = activity.filter((item) => matchesFilter(item, filter) && matchesQuery(item, query));

  function refresh() {
    startRefresh(() => router.refresh());
  }

  return <div className="activity-shell min-h-[calc(100dvh-64px)] px-4 py-6 pb-28 sm:px-6 lg:px-8 lg:py-8"><div className="mx-auto max-w-7xl">
    <header className="activity-header"><div><p className="section-kicker">CeloHT · Wallet</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight text-white sm:text-4xl">Activity</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-parchment-100/60">A single place to review confirmed wallet events and CeloHT activity.</p></div><div className="flex items-center gap-2"><button type="button" onClick={refresh} className="activity-refresh" disabled={refreshing} aria-label="Refresh activity"><RefreshCw size={16} className={refreshing ? "animate-spin" : ""} aria-hidden="true" /><span className="hidden sm:inline">Refresh</span></button>{!isConnected && <ConnectWalletButton />}</div></header>
    {wrongNetwork && <section className="activity-alert" role="alert"><ShieldAlert size={18} aria-hidden="true" /><div><h2 className="font-semibold text-white">Unsupported network</h2><p className="mt-1 text-sm text-parchment-100/60">Switch to Celo Mainnet or Celo Sepolia to inspect wallet activity.</p></div><button type="button" className="activity-secondary" onClick={() => switchChain({ chainId: celo.id })} disabled={isSwitching}>{isSwitching ? "Switching..." : "Switch to Celo"}</button></section>}
    <section className="activity-overview mt-7" aria-label="Activity overview"><OverviewItem icon={<WalletCards size={18} />} label="Wallet" value={isConnected && address ? shortenAddress(address) : "Not connected"} /><OverviewItem icon={<Activity size={18} />} label="Network" value={!isConnected ? "Disconnected" : wrongNetwork ? "Unsupported" : chain?.name ?? "Celo"} /><OverviewItem icon={<History size={18} />} label="Indexed events" value="Unavailable" /></section>
    {!isConnected ? <EmptyState icon={<WalletCards size={20} />} title="Connect your wallet to view activity" description="CeloHT can show wallet-linked events once an account is connected. No transactions are invented or loaded from demo data." action={<ConnectWalletButton />} /> : wrongNetwork ? <EmptyState icon={<ShieldAlert size={20} />} title="Activity is paused on this network" description="Connect to Celo Mainnet or Celo Sepolia to continue." /> : <><section className="activity-controls mt-7" aria-label="Activity filters"><div className="flex items-center gap-2"><Filter size={16} className="text-gold-300" aria-hidden="true" /><span className="text-xs font-semibold uppercase tracking-[0.16em] text-parchment-100/45">Filter</span></div><div className="activity-filters" role="group" aria-label="Filter activity">{filters.map((item) => <button type="button" key={item} aria-pressed={filter === item} onClick={() => setFilter(item)} className={`activity-filter ${filter === item ? "activity-filter-active" : ""}`}>{item}</button>)}</div><label className="activity-search"><span className="sr-only">Search hash or wallet address</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search hash or address" /></label></section>{visibleActivity.length === 0 ? <EmptyState icon={<Clock3 size={20} />} title={filter === "All" ? "No indexed activity yet" : `No ${filter.toLowerCase()} activity`} description="The CeloHT transaction indexer is not configured yet. Confirmed wallet events will appear here when a supported indexer is connected." /> : <div className="activity-list" aria-live="polite">{visibleActivity.map((item) => <ActivityCard key={item.hash} item={item} onSelect={setSelected} />)}</div>}</>}
    {selected && <ActivityDetails item={selected} onClose={() => setSelected(null)} />}
  </div></div>;
}

type ActivityItem = { hash: `0x${string}`; type: "sent" | "received" | "donation" | "agent" | "reforestation" | "swap" | "contract"; asset: "CELO" | "USDm"; amount: string; timestamp: number; status: "pending" | "confirmed" | "failed"; from: `0x${string}`; to: `0x${string}`; network: string; gasFee?: string; block?: string };
function matchesFilter(item: ActivityItem, filter: FilterName) { if (filter === "All") return true; if (filter === "Sent") return item.type === "sent"; if (filter === "Received") return item.type === "received"; if (filter === "Donations") return item.type === "donation"; if (filter === "Agent") return item.type === "agent"; if (filter === "Reforestation") return item.type === "reforestation"; return item.status === filter.toLowerCase(); }
function matchesQuery(item: ActivityItem, query: string) { const normalized = query.trim().toLowerCase(); return !normalized || item.hash.toLowerCase().includes(normalized) || item.from.toLowerCase().includes(normalized) || item.to.toLowerCase().includes(normalized); }
function OverviewItem({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="overview-item"><span>{icon}</span><div><p>{label}</p><strong>{value}</strong></div></div>; }
function ActivityCard({ item, onSelect }: { item: ActivityItem; onSelect: (item: ActivityItem) => void }) { const outgoing = item.type === "sent" || item.type === "donation" || item.type === "agent" || item.type === "reforestation"; return <button type="button" className="activity-card" onClick={() => onSelect(item)}><span className={`activity-type-icon activity-type-${item.type}`}>{outgoing ? <ArrowUpRight size={17} aria-hidden="true" /> : <ArrowDownLeft size={17} aria-hidden="true" />}</span><span className="activity-card-main"><strong>{item.type}</strong><small>{item.asset} · {new Date(item.timestamp).toLocaleString()}</small></span><span className="activity-card-amount"><strong>{outgoing ? "-" : "+"}{item.amount} {item.asset}</strong><small className={`activity-status activity-status-${item.status}`}>{item.status}</small></span></button>; }
function EmptyState({ icon, title, description, action }: { icon: React.ReactNode; title: string; description: string; action?: React.ReactNode }) { return <section className="activity-empty" role="status"><span className="activity-empty-icon">{icon}</span><div><h2 className="font-display text-lg font-semibold text-white">{title}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-parchment-100/55">{description}</p>{action && <div className="mt-4">{action}</div>}</div></section>; }
function ActivityDetails({ item, onClose }: { item: ActivityItem; onClose: () => void }) { const [copied, setCopied] = useState(false); async function copyHash() { await navigator.clipboard.writeText(item.hash); setCopied(true); window.setTimeout(() => setCopied(false), 1400); } return <div className="activity-drawer-backdrop" role="presentation" onClick={onClose}><aside className="activity-drawer" role="dialog" aria-modal="true" aria-labelledby="activity-detail-heading" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="section-kicker">Transaction details</p><h2 id="activity-detail-heading" className="mt-1 font-display text-xl font-semibold text-white">{item.type}</h2></div><button type="button" className="activity-close" onClick={onClose} aria-label="Close details">×</button></div><div className="mt-6 space-y-3"><DetailLine label="Status" value={item.status} /><DetailLine label="Asset / amount" value={`${item.amount} ${item.asset}`} /><DetailLine label="From" value={item.from} mono /><DetailLine label="To" value={item.to} mono /><DetailLine label="Network" value={item.network} /><DetailLine label="Block" value={item.block ?? "Unavailable"} /><DetailLine label="Gas fee" value={item.gasFee ?? "Unavailable"} /><DetailLine label="Timestamp" value={new Date(item.timestamp).toLocaleString()} /></div><div className="mt-6 border-t border-white/10 pt-5"><p className="text-xs text-parchment-100/45">Transaction hash</p><p className="mt-2 break-all font-mono text-xs text-parchment-100/68">{item.hash}</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={copyHash} className="activity-secondary">{copied ? <Check size={14} /> : <Copy size={14} />}{copied ? "Copied" : "Copy hash"}</button><a className="activity-secondary" href={`${item.network === "Celo Sepolia" ? "https://sepolia.celoscan.io" : "https://celoscan.io"}/tx/${item.hash}`} target="_blank" rel="noreferrer">View explorer <ExternalLink size={14} aria-hidden="true" /></a></div></div></aside></div>; }
function DetailLine({ label, value, mono }: { label: string; value: string; mono?: boolean }) { return <div className="detail-line"><span>{label}</span><strong className={mono ? "break-all text-right font-mono text-xs" : "text-right"}>{value}</strong></div>; }
