"use client";

import { useState } from "react";
import { ArrowDownLeft, ArrowUpRight, CheckCircle2, Clock3, Copy, ExternalLink, History, QrCode, Send, ShieldAlert, WalletCards } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { isAddress, parseUnits, type Address } from "viem";
import { celo, celoSepolia } from "wagmi/chains";
import { useAccount, useBalance, useChainId, useSendTransaction, useWaitForTransactionReceipt, useWriteContract } from "wagmi";
import { ConnectWalletButton } from "@/ConnectWalletButton";
import { erc20Abi, getUsdmAddress } from "@/lib/contracts";
import { formatTokenAmount, shortenAddress } from "@/lib/utils";

const supportedChains = new Set([celo.id, celoSepolia.id]);
type Asset = "CELO" | "USDm";

export default function WalletPage() {
  const { address, chain, isConnected } = useAccount();
  const chainId = useChainId();
  const [asset, setAsset] = useState<Asset>("CELO");
  const [recipient, setRecipient] = useState("");
  const [amount, setAmount] = useState("");
  const [copied, setCopied] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const celoBalance = useBalance({ address, query: { enabled: Boolean(address) } });
  const usdmAddress = getUsdmAddress(chainId);
  const usdmBalance = useBalance({ address, token: usdmAddress, query: { enabled: Boolean(address && usdmAddress) } });
  const { data: celoHash, error: celoError, isPending: isSendingCelo, sendTransaction } = useSendTransaction();
  const { data: usdmHash, error: usdmError, isPending: isSendingUsdm, writeContract } = useWriteContract();
  const hash = celoHash ?? usdmHash;
  const sendError = celoError ?? usdmError;
  const receipt = useWaitForTransactionReceipt({ hash });
  const wrongNetwork = isConnected && !supportedChains.has(chainId);
  const selectedBalance = asset === "CELO" ? celoBalance.data : usdmBalance.data;
  const decimals = selectedBalance?.decimals ?? 18;
  const recipientValid = isAddress(recipient) && recipient.toLowerCase() !== "0x0000000000000000000000000000000000000000";
  let parsedAmount: bigint | undefined;
  try { parsedAmount = amount ? parseUnits(amount, decimals) : undefined; } catch { parsedAmount = undefined; }
  const amountValid = parsedAmount !== undefined && parsedAmount > 0n;
  const enoughBalance = Boolean(parsedAmount !== undefined && selectedBalance && parsedAmount <= selectedBalance.value);
  const canSend = Boolean(isConnected && !wrongNetwork && recipientValid && amountValid && enoughBalance && !isSendingCelo && !isSendingUsdm && !hash && (asset === "CELO" || usdmAddress));
  const amountError = amount && (!amountValid ? `Enter a valid ${asset} amount.` : !enoughBalance ? `Insufficient ${asset} balance.` : undefined);

  function handleSend() {
    if (!canSend || !parsedAmount) return;
    setSubmitted(true);
    if (asset === "CELO") sendTransaction({ to: recipient as Address, value: parsedAmount });
    else if (usdmAddress) writeContract({ address: usdmAddress, abi: erc20Abi, functionName: "transfer", args: [recipient as Address, parsedAmount] });
  }
  async function copyAddress() { if (!address) return; await navigator.clipboard.writeText(address); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }
  function resetSend() { setSubmitted(false); setAmount(""); setRecipient(""); }

  return <div className="wallet-shell min-h-[calc(100dvh-64px)] px-4 py-6 pb-28 sm:px-6 lg:px-8 lg:py-8"><div className="mx-auto max-w-7xl">
    <header className="wallet-header"><div><p className="section-kicker">CeloHT · Financial terminal</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight text-white sm:text-4xl">Wallet</h1><p className="mt-2 text-sm text-parchment-100/58">Manage live Celo assets, review transfers, and keep every confirmation in your wallet.</p></div><div className="wallet-connection"><div><p className="text-xs text-parchment-100/42">Wallet</p><p className="mt-1 font-mono text-xs text-white">{isConnected && address ? shortenAddress(address) : "Not connected"}</p></div>{!isConnected && <ConnectWalletButton />}</div></header>
    <section className="portfolio-panel mt-7" aria-labelledby="portfolio-heading"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="section-kicker">Portfolio</p><h2 id="portfolio-heading" className="mt-1 font-display text-2xl font-semibold text-white">Total portfolio value</h2><p className="mt-2 text-sm text-parchment-100/50">Market valuation is unavailable until a live price source is configured.</p></div><span className={`network-badge ${wrongNetwork ? "network-badge-warning" : ""}`}><span className="status-dot" />{!isConnected ? "Disconnected" : wrongNetwork ? "Unsupported network" : chain?.name ?? "Celo"}</span></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="portfolio-total"><span>Estimated USD value</span><strong>Unavailable</strong><small>Live market data not configured</small></div><AssetRow label="CELO" value={isConnected ? celoBalance.isLoading ? "Loading" : celoBalance.error ? "Unavailable" : formatTokenAmount(celoBalance.data?.value ?? 0n, celoBalance.data?.decimals ?? 18) : "Not connected"} detail="Native asset · gas" /><AssetRow label="USDm" value={isConnected ? usdmBalance.isLoading ? "Loading" : usdmBalance.error ? "Unavailable" : usdmBalance.data ? formatTokenAmount(usdmBalance.data.value, usdmBalance.data.decimals) : "Unavailable" : "Not connected"} detail="Celo stable asset" /></div></section>
    <section className="quick-actions mt-5" aria-labelledby="quick-actions-heading"><div><p className="section-kicker">Actions</p><h2 id="quick-actions-heading" className="mt-1 font-display text-xl font-semibold text-white">Move funds</h2></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><ActionLink href="#send" icon={<Send size={18} />} label="Send" /><ActionLink href="#receive" icon={<ArrowDownLeft size={18} />} label="Receive" /><button type="button" disabled className="wallet-action wallet-action-disabled"><ArrowUpRight size={18} aria-hidden="true" /><span>Swap</span><small>Unavailable</small></button><ActionLink href="#history" icon={<History size={18} />} label="History" /></div></section>
    <div className="mt-7 grid gap-5 xl:grid-cols-[1.15fr_0.85fr]"><section id="send" className="wallet-panel" aria-labelledby="send-heading"><div className="flex items-start justify-between gap-3"><div><p className="section-kicker">Transfer</p><h2 id="send-heading" className="mt-1 font-display text-xl font-semibold text-white">Send assets</h2></div><Send size={21} className="text-gold-300" aria-hidden="true" /></div><p className="mt-2 text-sm text-parchment-100/55">Review the recipient, asset, amount, and network before your wallet signs.</p><div className="mt-6 grid gap-4"><FieldLabel htmlFor="asset">Asset</FieldLabel><select id="asset" value={asset} onChange={(event) => { setAsset(event.target.value as Asset); setAmount(""); }} className="wallet-input"><option value="CELO">CELO</option><option value="USDm">USDm</option></select><FieldLabel htmlFor="recipient">Recipient address</FieldLabel><input id="recipient" value={recipient} onChange={(event) => setRecipient(event.target.value)} placeholder="0x..." aria-invalid={Boolean(recipient) && !recipientValid} className="wallet-input" />{recipient && !recipientValid && <p className="wallet-error" role="alert">Enter a valid non-zero EVM address.</p>}<div className="flex items-center justify-between gap-3"><FieldLabel htmlFor="send-amount">Amount</FieldLabel><span className="text-xs text-parchment-100/45">Available: {selectedBalance ? formatTokenAmount(selectedBalance.value, selectedBalance.decimals) : "Not connected"}</span></div><input id="send-amount" type="number" min="0" step="any" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0.00" aria-invalid={Boolean(amountError)} className="wallet-input wallet-amount" />{amountError && <p className="wallet-error" role="alert">{amountError}</p>}{asset === "USDm" && !usdmAddress && <p className="wallet-warning" role="alert">USDm is unavailable on this network.</p>}<button type="button" onClick={handleSend} disabled={!canSend} className="wallet-primary"><Send size={16} aria-hidden="true" />{isSendingCelo || isSendingUsdm ? "Confirm in wallet" : `Review ${asset} transfer`}</button>{!isConnected && <p className="text-sm text-parchment-100/52">Connect your wallet before preparing a transfer.</p>}{sendError && <p className="wallet-error" role="alert">{sendError.message.toLowerCase().includes("rejected") ? "The transaction was cancelled in your wallet. No funds moved." : "The transaction could not be completed. Check your wallet, network, and balance."}</p>}</div></section><TransactionReview submitted={submitted} recipient={recipient} asset={asset} amount={amount} chain={chain} hash={hash} isSending={isSendingCelo || isSendingUsdm} isConfirming={receipt.isLoading} isConfirmed={receipt.isSuccess} isFailed={receipt.isError} onReset={resetSend} /></div>
    <section id="receive" className="wallet-panel mt-5" aria-labelledby="receive-heading"><div className="flex items-start justify-between gap-3"><div><p className="section-kicker">Receive</p><h2 id="receive-heading" className="mt-1 font-display text-xl font-semibold text-white">Your wallet address</h2></div><QrCode size={21} className="text-gold-300" aria-hidden="true" /></div>{address ? <div className="mt-5 flex flex-col items-start gap-5 sm:flex-row sm:items-center"><div className="qr-frame"><QRCodeSVG value={address} size={148} includeMargin /></div><div className="min-w-0"><p className="break-all font-mono text-sm text-parchment-100/75">{address}</p><button type="button" onClick={copyAddress} className="wallet-secondary mt-4"><Copy size={15} aria-hidden="true" />{copied ? "Copied" : "Copy address"}</button><p className="mt-3 text-xs leading-5 text-parchment-100/45">Only share this public address. Receive CELO and USDm on the selected Celo network.</p></div></div> : <div className="empty-wallet"><WalletCards size={19} aria-hidden="true" /><p>Connect a wallet to create a receive address and QR code.</p><ConnectWalletButton /></div>}</section>
    <section id="history" className="wallet-panel mt-5" aria-labelledby="history-heading"><div className="flex items-start justify-between gap-3"><div><p className="section-kicker">History</p><h2 id="history-heading" className="mt-1 font-display text-xl font-semibold text-white">Confirmed activity</h2></div><History size={21} className="text-gold-300" aria-hidden="true" /></div><div className="empty-wallet mt-5"><Clock3 size={19} aria-hidden="true" /><div><p className="text-sm font-medium text-parchment-100/75">No in-app transactions yet</p><p className="mt-1 text-xs leading-5 text-parchment-100/45">A CeloHT transaction indexer is not configured. Confirmed wallet activity is not fabricated here.</p></div>{isConnected && address && <a className="wallet-secondary" href={`${explorerUrl(chainId)}/address/${address}`} target="_blank" rel="noreferrer">Open explorer <ExternalLink size={14} aria-hidden="true" /></a>}</div></section>
  </div></div>;
}

function AssetRow({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="asset-row"><span className="asset-symbol">{label === "CELO" ? "C" : "U"}</span><div><p className="text-sm font-semibold text-white">{label}</p><p className="mt-1 text-xs text-parchment-100/42">{detail}</p></div><strong className="ml-auto font-mono text-sm text-white">{value}</strong></div>; }
function ActionLink({ href, icon, label }: { href: string; icon: React.ReactNode; label: string }) { return <a href={href} className="wallet-action"><span>{icon}</span><span>{label}</span></a>; }
function FieldLabel({ htmlFor, children }: { htmlFor: string; children: React.ReactNode }) { return <label htmlFor={htmlFor} className="text-xs font-semibold uppercase tracking-[0.16em] text-parchment-100/52">{children}</label>; }
function ReviewLine({ label, value, mono }: { label: string; value: string; mono?: boolean }) { return <div className="review-line"><span>{label}</span><strong className={mono ? "break-all text-right font-mono text-xs" : "text-right"}>{value}</strong></div>; }
function TransactionReview({ submitted, recipient, asset, amount, chain, hash, isSending, isConfirming, isConfirmed, isFailed, onReset }: { submitted: boolean; recipient: string; asset: Asset; amount: string; chain?: { name?: string }; hash?: `0x${string}`; isSending: boolean; isConfirming: boolean; isConfirmed: boolean; isFailed: boolean; onReset: () => void }) { return <section className="wallet-panel" aria-labelledby="review-heading"><div className="flex items-start justify-between gap-3"><div><p className="section-kicker">Review & status</p><h2 id="review-heading" className="mt-1 font-display text-xl font-semibold text-white">Transaction details</h2></div><ShieldAlert size={21} className="text-cyan-300" aria-hidden="true" /></div>{!submitted ? <div className="review-empty"><p>Recipient, amount, network fee, and total will appear here before submission.</p><span>Wallet approval is always required.</span></div> : <div className="review-details"><ReviewLine label="From" value="Connected wallet" /><ReviewLine label="To" value={recipient || "Not provided"} mono /><ReviewLine label="Asset / amount" value={`${amount || "0"} ${asset}`} /><ReviewLine label="Network" value={chain?.name ?? "Celo network"} /><ReviewLine label="Network fee" value="Estimated in wallet" /><div className="transaction-state">{isSending ? <><Clock3 size={16} /> Waiting for wallet signature</> : isConfirming ? <><Clock3 size={16} /> Transaction submitted, confirming on-chain</> : isConfirmed ? <><CheckCircle2 size={16} /> Transfer confirmed</> : isFailed ? <><ShieldAlert size={16} /> Transfer failed or reverted</> : hash ? "Transaction submitted" : "Awaiting wallet response"}</div>{hash && <><p className="text-xs text-parchment-100/45">Transaction hash</p><p className="break-all font-mono text-xs text-parchment-100/65">{hash}</p><a className="wallet-secondary" href={`${explorerUrl(chain?.name === "Celo Sepolia" ? celoSepolia.id : celo.id)}/tx/${hash}`} target="_blank" rel="noreferrer">View transaction <ExternalLink size={14} aria-hidden="true" /></a></>}{(isConfirmed || isFailed) && <button type="button" onClick={onReset} className="wallet-secondary">Start another transfer</button>}</div>}</section>; }
function explorerUrl(chainId: number) { return chainId === celoSepolia.id ? "https://sepolia.celoscan.io" : "https://celoscan.io"; }
