/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAgentRegistry {
  export type AgentStruct = {
    wallet: AddressLike;
    metadataURI: string;
    status: BigNumberish;
    registeredAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type AgentStructOutput = [
    wallet: string,
    metadataURI: string,
    status: bigint,
    registeredAt: bigint,
    updatedAt: bigint
  ] & {
    wallet: string;
    metadataURI: string;
    status: bigint;
    registeredAt: bigint;
    updatedAt: bigint;
  };
}

export interface IAgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveAgent"
      | "getAgent"
      | "isActiveAgent"
      | "registerAgent"
      | "reinstateAgent"
      | "suspendAgent"
      | "totalAgents"
      | "updateMetadata"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentApproved"
      | "AgentMetadataUpdated"
      | "AgentRegistered"
      | "AgentReinstated"
      | "AgentSuspended"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "reinstateAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "suspendAgent",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateMetadata",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isActiveAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reinstateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suspendAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMetadata",
    data: BytesLike
  ): Result;
}

export namespace AgentApprovedEvent {
  export type InputTuple = [wallet: AddressLike, approvedBy: AddressLike];
  export type OutputTuple = [wallet: string, approvedBy: string];
  export interface OutputObject {
    wallet: string;
    approvedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentMetadataUpdatedEvent {
  export type InputTuple = [wallet: AddressLike, metadataURI: string];
  export type OutputTuple = [wallet: string, metadataURI: string];
  export interface OutputObject {
    wallet: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [wallet: AddressLike, metadataURI: string];
  export type OutputTuple = [wallet: string, metadataURI: string];
  export interface OutputObject {
    wallet: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentReinstatedEvent {
  export type InputTuple = [wallet: AddressLike, reinstatedBy: AddressLike];
  export type OutputTuple = [wallet: string, reinstatedBy: string];
  export interface OutputObject {
    wallet: string;
    reinstatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentSuspendedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    suspendedBy: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    wallet: string,
    suspendedBy: string,
    reason: string
  ];
  export interface OutputObject {
    wallet: string;
    suspendedBy: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IAgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: IAgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveAgent: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  getAgent: TypedContractMethod<
    [wallet: AddressLike],
    [IAgentRegistry.AgentStructOutput],
    "view"
  >;

  isActiveAgent: TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  registerAgent: TypedContractMethod<
    [metadataURI: string],
    [void],
    "nonpayable"
  >;

  reinstateAgent: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  suspendAgent: TypedContractMethod<
    [wallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  totalAgents: TypedContractMethod<[], [bigint], "view">;

  updateMetadata: TypedContractMethod<
    [metadataURI: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveAgent"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [IAgentRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActiveAgent"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<[metadataURI: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reinstateAgent"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "suspendAgent"
  ): TypedContractMethod<
    [wallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateMetadata"
  ): TypedContractMethod<[metadataURI: string], [void], "nonpayable">;

  getEvent(
    key: "AgentApproved"
  ): TypedContractEvent<
    AgentApprovedEvent.InputTuple,
    AgentApprovedEvent.OutputTuple,
    AgentApprovedEvent.OutputObject
  >;
  getEvent(
    key: "AgentMetadataUpdated"
  ): TypedContractEvent<
    AgentMetadataUpdatedEvent.InputTuple,
    AgentMetadataUpdatedEvent.OutputTuple,
    AgentMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentReinstated"
  ): TypedContractEvent<
    AgentReinstatedEvent.InputTuple,
    AgentReinstatedEvent.OutputTuple,
    AgentReinstatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentSuspended"
  ): TypedContractEvent<
    AgentSuspendedEvent.InputTuple,
    AgentSuspendedEvent.OutputTuple,
    AgentSuspendedEvent.OutputObject
  >;

  filters: {
    "AgentApproved(address,address)": TypedContractEvent<
      AgentApprovedEvent.InputTuple,
      AgentApprovedEvent.OutputTuple,
      AgentApprovedEvent.OutputObject
    >;
    AgentApproved: TypedContractEvent<
      AgentApprovedEvent.InputTuple,
      AgentApprovedEvent.OutputTuple,
      AgentApprovedEvent.OutputObject
    >;

    "AgentMetadataUpdated(address,string)": TypedContractEvent<
      AgentMetadataUpdatedEvent.InputTuple,
      AgentMetadataUpdatedEvent.OutputTuple,
      AgentMetadataUpdatedEvent.OutputObject
    >;
    AgentMetadataUpdated: TypedContractEvent<
      AgentMetadataUpdatedEvent.InputTuple,
      AgentMetadataUpdatedEvent.OutputTuple,
      AgentMetadataUpdatedEvent.OutputObject
    >;

    "AgentRegistered(address,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentReinstated(address,address)": TypedContractEvent<
      AgentReinstatedEvent.InputTuple,
      AgentReinstatedEvent.OutputTuple,
      AgentReinstatedEvent.OutputObject
    >;
    AgentReinstated: TypedContractEvent<
      AgentReinstatedEvent.InputTuple,
      AgentReinstatedEvent.OutputTuple,
      AgentReinstatedEvent.OutputObject
    >;

    "AgentSuspended(address,address,string)": TypedContractEvent<
      AgentSuspendedEvent.InputTuple,
      AgentSuspendedEvent.OutputTuple,
      AgentSuspendedEvent.OutputObject
    >;
    AgentSuspended: TypedContractEvent<
      AgentSuspendedEvent.InputTuple,
      AgentSuspendedEvent.OutputTuple,
      AgentSuspendedEvent.OutputObject
    >;
  };
}
