/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IImpactRegistry {
  export type PlantingRecordStruct = {
    projectId: BytesLike;
    reportedBy: AddressLike;
    treeCount: BigNumberish;
    evidenceURI: string;
    recordedAt: BigNumberish;
  };

  export type PlantingRecordStructOutput = [
    projectId: string,
    reportedBy: string,
    treeCount: bigint,
    evidenceURI: string,
    recordedAt: bigint
  ] & {
    projectId: string;
    reportedBy: string;
    treeCount: bigint;
    evidenceURI: string;
    recordedAt: bigint;
  };
}

export interface IImpactRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createProject"
      | "getRecord"
      | "recordCount"
      | "recordPlanting"
      | "totalTreesFor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PlantingRecorded" | "ProjectCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createProject",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordPlanting",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalTreesFor",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPlanting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTreesFor",
    data: BytesLike
  ): Result;
}

export namespace PlantingRecordedEvent {
  export type InputTuple = [
    projectId: BytesLike,
    recordId: BigNumberish,
    reportedBy: AddressLike,
    treeCount: BigNumberish
  ];
  export type OutputTuple = [
    projectId: string,
    recordId: bigint,
    reportedBy: string,
    treeCount: bigint
  ];
  export interface OutputObject {
    projectId: string;
    recordId: bigint;
    reportedBy: string;
    treeCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectCreatedEvent {
  export type InputTuple = [projectId: BytesLike, metadataURI: string];
  export type OutputTuple = [projectId: string, metadataURI: string];
  export interface OutputObject {
    projectId: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IImpactRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IImpactRegistry;
  waitForDeployment(): Promise<this>;

  interface: IImpactRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createProject: TypedContractMethod<
    [projectId: BytesLike, metadataURI: string],
    [void],
    "nonpayable"
  >;

  getRecord: TypedContractMethod<
    [recordId: BigNumberish],
    [IImpactRegistry.PlantingRecordStructOutput],
    "view"
  >;

  recordCount: TypedContractMethod<[], [bigint], "view">;

  recordPlanting: TypedContractMethod<
    [projectId: BytesLike, treeCount: BigNumberish, evidenceURI: string],
    [bigint],
    "nonpayable"
  >;

  totalTreesFor: TypedContractMethod<[projectId: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createProject"
  ): TypedContractMethod<
    [projectId: BytesLike, metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [recordId: BigNumberish],
    [IImpactRegistry.PlantingRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordPlanting"
  ): TypedContractMethod<
    [projectId: BytesLike, treeCount: BigNumberish, evidenceURI: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalTreesFor"
  ): TypedContractMethod<[projectId: BytesLike], [bigint], "view">;

  getEvent(
    key: "PlantingRecorded"
  ): TypedContractEvent<
    PlantingRecordedEvent.InputTuple,
    PlantingRecordedEvent.OutputTuple,
    PlantingRecordedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectCreated"
  ): TypedContractEvent<
    ProjectCreatedEvent.InputTuple,
    ProjectCreatedEvent.OutputTuple,
    ProjectCreatedEvent.OutputObject
  >;

  filters: {
    "PlantingRecorded(bytes32,uint256,address,uint32)": TypedContractEvent<
      PlantingRecordedEvent.InputTuple,
      PlantingRecordedEvent.OutputTuple,
      PlantingRecordedEvent.OutputObject
    >;
    PlantingRecorded: TypedContractEvent<
      PlantingRecordedEvent.InputTuple,
      PlantingRecordedEvent.OutputTuple,
      PlantingRecordedEvent.OutputObject
    >;

    "ProjectCreated(bytes32,string)": TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
    ProjectCreated: TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
  };
}
