/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAgentRegistry } from "./IAgentRegistry";
export type { ICertificateRegistry } from "./ICertificateRegistry";
export type { IDonationManager } from "./IDonationManager";
export type { IImpactRegistry } from "./IImpactRegistry";
