/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  BasisPoints,
  BasisPointsInterface,
} from "../../../contracts/libraries/BasisPoints";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "BasisPointsOverflow",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212201e9715b9844755b74d3428199fa787ba14ec95c50578f3e7a2a54677058a019364736f6c634300081b0033";

type BasisPointsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BasisPointsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BasisPoints__factory extends ContractFactory {
  constructor(...args: BasisPointsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BasisPoints & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BasisPoints__factory {
    return super.connect(runner) as BasisPoints__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BasisPointsInterface {
    return new Interface(_abi) as BasisPointsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): BasisPoints {
    return new Contract(address, _abi, runner) as unknown as BasisPoints;
  }
}
