/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IImpactRegistry,
  IImpactRegistryInterface,
} from "../../../contracts/interfaces/IImpactRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "projectId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "recordId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "reportedBy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "treeCount",
        type: "uint32",
      },
    ],
    name: "PlantingRecorded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "projectId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "metadataURI",
        type: "string",
      },
    ],
    name: "ProjectCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "projectId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "metadataURI",
        type: "string",
      },
    ],
    name: "createProject",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "recordId",
        type: "uint256",
      },
    ],
    name: "getRecord",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "projectId",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "reportedBy",
            type: "address",
          },
          {
            internalType: "uint32",
            name: "treeCount",
            type: "uint32",
          },
          {
            internalType: "string",
            name: "evidenceURI",
            type: "string",
          },
          {
            internalType: "uint64",
            name: "recordedAt",
            type: "uint64",
          },
        ],
        internalType: "struct IImpactRegistry.PlantingRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "recordCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "projectId",
        type: "bytes32",
      },
      {
        internalType: "uint32",
        name: "treeCount",
        type: "uint32",
      },
      {
        internalType: "string",
        name: "evidenceURI",
        type: "string",
      },
    ],
    name: "recordPlanting",
    outputs: [
      {
        internalType: "uint256",
        name: "recordId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "projectId",
        type: "bytes32",
      },
    ],
    name: "totalTreesFor",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IImpactRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IImpactRegistryInterface {
    return new Interface(_abi) as IImpactRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IImpactRegistry {
    return new Contract(address, _abi, runner) as unknown as IImpactRegistry;
  }
}
