/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAgentRegistry__factory } from "./IAgentRegistry__factory";
export { ICertificateRegistry__factory } from "./ICertificateRegistry__factory";
export { IDonationManager__factory } from "./IDonationManager__factory";
export { IImpactRegistry__factory } from "./IImpactRegistry__factory";
